apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: bariyard/multi-client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.html'
    - image: bariyard/multi-server
      context: ./server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bariyard/multi-worker
      context: ./worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/client-cluster-ip-service.yml
      - k8s/server-cluster-ip-service.yml