apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - '*.k8s-multi.com'
  - k8s-multi.com
  - k8s-multi.org