apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: graphql-server
  template:
    metadata:
      labels:
        component: graphql-server
    spec:
      containers:
        - name: server
          image: bariyard/multi-graphql-server
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: pgpassword
                  key: PGPASSWORD